### ISSUE TITLE
Target class [fcm.sender] does not exist.

### ISSUE THREAD

**Issue by marispro** [code-lts/Laravel-FCM#12]
Hi, having issue on Laravel 8 latest version,
`Illuminate \ Contracts \ Container \ BindingResolutionException

Target class [fcm.sender] does not exist.`

Code used exactly as it is in example. So this error comes from FCM::sendTo() method.

**Comment by marispro** [comment]
Sorry, issue was that artisan couldn't clean cache folder and did not throw any errors.
Who will have similar issue, just delete contents of /bootstrap/cache folder.

**Comment by williamdes** [comment]
Thank you, it is better to report than not :)
