### ISSUE TITLE
send notification issue

### ISSUE THREAD

**Issue by quocthi2005** [code-lts/Laravel-FCM#15]
Hello,
I got this issue

I don't get a notification when I send 10 thousand devices

**Comment by williamdes** [comment]
Hello
Sorry for the reponse time, could you provide some code ?

**Comment by lalithhakari** [comment]
i have read that "You can specify up to 500 device registration tokens per invocation."
find more info in this link [https://firebase.google.com/docs/cloud-messaging/send-message#send-messages-to-multiple-devices](url)

**Comment by Stevemoretz** [comment]
> Hello, I got this issue
> 
> I don't get a notification when I send 10 thousand devices

You can't it has a limit send 500 at a time.

**Comment by williamdes** [comment]
Thanks for clarifying !
