### ISSUE TITLE
getContainer() must be public

### ISSUE THREAD

**Issue by hirakujira** [code-lts/Laravel-FCM#16]
Since laravel 8.33.1, `getContainer()` function must be public

Reference: [https://github.com/laravel/framework/commit/90fbaa7ec53410508cd73c09e3f788e458dd8b92](https://github.com/laravel/framework/commit/90fbaa7ec53410508cd73c09e3f788e458dd8b92)

**Comment by williamdes** [comment]
Thank you for the notice
I will apply that if it does not break anything

**Comment by hirakujira** [comment]
I'm not sure whether it breaks anything, but it would show error and not compatible with laravel 8.33.1 and newer versions if the function keeps private.

**Comment by williamdes** [comment]
Yup, as far as I can see on https://laravel.com/api/5.8/Illuminate/Support/Manager.html and the actual code there is no `getContainer` defined, that allow me to change the function signature to what I want 🎉

**Comment by williamdes** [comment]
I released [1.6.2](https://github.com/code-lts/Laravel-FCM/releases/tag/1.6.2) 🚀
