### ISSUE TITLE
support for laravel 9 and php 8.1

### ISSUE THREAD

**Issue by m-ostadi** [code-lts/Laravel-FCM#18]
Hi, thanks for your efforts on maintaining this package.
Would you mind adding support for php 8.1 and laravel 9?

**Comment by williamdes** [comment]
Hi @MOstadi 
Thank you for this kind message, I already pushed a fix for Laravel 9 (9a5b9239dfa2bb3dc091b8cc6c65f2a89ed7f381) and PHP 8.1 is already supported 🎉 
And it works !
Do you need this very soon or can you use composer `dev-main#9a5b9239dfa2bb3dc091b8cc6c65f2a89ed7f381` version while I make some more changes before a release ?

**Comment by m-ostadi** [comment]
Thanks for your quick response, yes it's enough for now. I can wait for release.

**Comment by williamdes** [comment]
> Thanks for your quick response, yes it's enough for now. I can wait for release.

Done in [1.7.0](https://github.com/code-lts/Laravel-FCM/releases/tag/1.7.0) 🚀 
Let me know if that works as expected :)
