### ISSUE TITLE
[Enhancement] Add Retry-After header upon 200 response status

### ISSUE THREAD

**Issue by quyle92** [code-lts/Laravel-FCM#20]
Hi,
<img width="717" alt="image" src="https://user-images.githubusercontent.com/59790219/167393583-99c4c298-cc39-4e8c-8ca2-72a8eb35f666.png">
The [FCM doc ](https://firebase.google.com/docs/cloud-messaging/http-server-ref#error-codes)mentions about  honoring the Retry-After header if it is included in the response from the FCM Connection Server in case of Timeout error. So I'd like to add a few line of codes in  `DownstreamResponse.php` to reflect that feature:

```php
...
protected $retryAfter;

public function __construct(ResponseInterface $response, $tokens, Logger $logger)
{
     $this->tokens = is_string($tokens) ? [$tokens] : $tokens;
     $this->retryAfterHeader($response);

     parent::__construct($response, $logger);
}

public function retryAfterHeader($response)
{
      $responseHeader = $response->getHeaders();
      if (array_key_exists('Retry-After', $responseHeader)) {
            $this->retryAfter = $responseHeader['Retry-After'][0];
      }
}

public function getRetryAfterHeaderValue()
{
      return $this->retryAfter;
}
```
Unit test:
```php
public function testResponsekWithRetryAfterHeader()
{
     $retry_after = 1;
     $tokens = [
          'first_token'
     ];

     $response = new Response(200, ['Retry-After' => $retry_after], 
                   '{
			 "multicast_id": 216,
			 "success": 0,
			 "failure": 1,
			"canonical_ids": 0,
		         "results": [
				{ "error": "DeviceMessageRateExceeded" }
	                 ]
	}');

     $logger = new \Monolog\Logger('test');
     $logger->pushHandler(new \Monolog\Handler\NullHandler());

     $downstreamResponse = new DownstreamResponse($response, $tokens, $logger);

     $this->assertEquals($retry_after, $downstreamResponse->getRetryAfterHeaderValue());
}
```

**Comment by quyle92** [comment]
Hi,
any update on this?

**Comment by williamdes** [comment]
Hi @quyle92 
I am very sorry, I was thinking about answering directly, seems like I forgot
Thank you so much for this contribution, I will investigate about it and add this in a new version

**Comment by williamdes** [comment]
Hi @quyle92 

I think it would be better to change `BaseResponse::checkIsJsonResponse` to throw a `ServerResponseException` when there is a `Retry-After` header

Is your response data from a production environment or did you copy paste the response ?
Because I think responses could be more like (copied from a Sentry reporting production instance)
```html
<!DOCTYPE html>
<html lang=en>
  <meta charset=utf-8>
  <meta name=viewport content="initial-scale=1, minimum-scale=1, w (truncated...)
```

**Comment by quyle92** [comment]
Hi @williamdes ,
Thanks for your reply.
If `ServerResponseException` is thrown, then I think we cannot get the `$downstreamResponse` from which to extract the retried fcm_tokens (so as to do the `$job->release()` right after that). It's because when exception is thrown, it will directly go to `failed()` function of laravel queue job).
Regarding the response data, it is the  test response that I takes from `vendor/code-lts/laravel-fcm/tests/DownstreamResponseTest.php`.

**Comment by williamdes** [comment]
> 

Hi @quyle92 

Okay, but can you confirm that in production you have a response from FCM saying both success and retry after ?
For me that would not make sense, but maybe it exists ?
Do you have some proof ?

If it does not exist then we have only one case to handle that is: handle a response 200 HTML (example above) with a retry after header. Probably because they had a server error.

**Comment by quyle92** [comment]
Hi @williamdes ,
I've never experienced an FCM response 200 together with retried tokens so can't post it here. But I wonder if FCM returns HTML response like above then how could we know what tokens to be retried later are?
If possible can you please post that full HTML response from Sentry?

**Comment by williamdes** [comment]
> Hi @williamdes , I've never experienced an FCM response 200 together with retried tokens so can't post it here. But I wonder if FCM returns HTML response like above then how could we know what tokens to be retried later are? If possible can you please post that full HTML response from Sentry?

I just pushed some changes into production so I can collect debug data and let you know what content is sent back and what are the headers

**Comment by williamdes** [comment]
Hi !

Nothing was found on my logs but I implemented some of your work into da80938e478914d20ada5d9d8710bdcf3f010b0c

**Comment by williamdes** [comment]
I think we can say it is implemented now :)

**Comment by williamdes** [comment]
Released ! 🎉 
https://github.com/code-lts/Laravel-FCM/releases/tag/1.8.0
