### ISSUE TITLE
Google API deprecation

### ISSUE THREAD

**Issue by marconett** [code-lts/Laravel-FCM#23]
The method this API used talk to FCM was deprecated by Google an will stop working after June 2024.

Quote:
> Sending messages (including upstream messages) with the FCM XMPP and HTTP legacy APIs was deprecated on June 20, 2023, and will be removed in June 2024. If you are using the legacy send APIs, we strongly recommend that you [migrate to the HTTP v1 API](https://firebase.google.com/docs/cloud-messaging/migrate-v1) or consider using the [Admin SDK](https://firebase.google.com/docs/cloud-messaging/server#choosing-a-server-option) to build send requests.

Source: https://firebase.google.com/docs/cloud-messaging/http-server-ref

**Comment by williamdes** [comment]
Can you please comment on #9?
It's about this topic :)

**Comment by williamdes** [comment]
Duplicate of #9

**Comment by marconett** [comment]
Sorry, I didn't look at #9 before because its title is misleading and the date that issue was created predates the deprecation by two years.

But yes, the same problem is being discussed in there.

**Comment by williamdes** [comment]
No worries, but I think it's important you share your feedback if any on #9

**Comment by marconett** [comment]
I just wanted to inform maintainers about the deprecation.
I don't have any relevant feedback. I was evaluating libraries but decided to write FCM notification handling myself.
