### ISSUE TITLE
Add support for fcmOptions

### ISSUE THREAD

**Issue by mathieu21** [code-lts/Laravel-FCM#3]
Add support for fcmOptions: https://firebase.google.com/docs/reference/fcm/rest/v1/projects.messages#AndroidFcmOptions

Including Analytics labels used to filter data in Firebase

**Comment by williamdes** [comment]
Hi @mathieu21 
Could you test this before a release is done ?

**Comment by techfaceus** [comment]
When send Push with analyticsLabel, it not shown at Firebase Chart.

**Comment by williamdes** [comment]
See: https://github.com/ToothlessGear/node-gcm/issues/340#issuecomment-663800667

> Indeed this parameter is not supported in the FCM Legacy HTTP Server API.

So we need to migrate to V1 API, see #9 

cc @mathieu21

**Comment by quocthi2005** [comment]
Hi @williamdes 
How to add analyticsLabel to the message?
Firebase has a feature to set this.
https://firebase.google.com/docs/cloud-messaging/understand-delivery#adding-analytics-labels-to-messages

How to set this in this package?

**Comment by williamdes** [comment]
Hi!


> we need to migrate to V1 API, see #9

The current API does not take the analytics label in account. So we need to migrate to the new API.
Do you want to help?

**Comment by quocthi2005** [comment]
Thank you @williamdes 

> Do you want to help?

Yes, it's great

**Comment by williamdes** [comment]
> Thank you @williamdes
> 
> > Do you want to help?
> 
> Yes, it's great

Feel free to send pull-requests

**Comment by quocthi2005** [comment]
Hi @williamdes 
> So we need to migrate to the new API.

Can you explain in more detail?

**Comment by williamdes** [comment]
See https://github.com/code-lts/Laravel-FCM/issues/9
