### ISSUE TITLE
Support guzzle 7

### ISSUE THREAD

**Issue by yaakam** [code-lts/Laravel-FCM#6]

**Comment by williamdes** [comment]
Thank you for the report! 

https://github.com/code-lts/Laravel-FCM/blob/3e9e621f456d1fe7ca24c4b62938f49e84d1a024/composer.json#L20

**Comment by williamdes** [comment]
Hi @yaakam  
Could you please let me know if my fix works fine for you ?
Using the `dev-main` version of this package (https://packagist.org/packages/code-lts/laravel-fcm#dev-main)

**Comment by williamdes** [comment]
I released [1.6.0](https://github.com/code-lts/Laravel-FCM/releases/tag/1.6.0) :tada:

**Comment by yaakam** [comment]
Hi @williamdes,
It works perfectly for me :rocket:
