### ISSUE TITLE
Sending to multiple group_keys with array fails

### ISSUE THREAD

**Issue by Stevemoretz** [code-lts/Laravel-FCM#7]
First of all the logger gives an error because it can't use array in string "...->to" if you turn it off,Now there is no error.
The response failedTokensNumber you get 1.

**Comment by williamdes** [comment]
Could you paste a code example please ?

**Comment by Stevemoretz** [comment]
> Could you paste a code example please ?

I'm sorry I wasn't clear just use the [readme.md example for sending a group message](https://github.com/code-lts/Laravel-FCM#group-messages) it is using an array in the example and the above problems happen.

**Comment by williamdes** [comment]
Okay, maybe the README is wrong then :p

https://github.com/code-lts/Laravel-FCM/blob/3e9e621f456d1fe7ca24c4b62938f49e84d1a024/src/Sender/FCMSender.php#L66
https://github.com/code-lts/Laravel-FCM/blob/3e9e621f456d1fe7ca24c4b62938f49e84d1a024/src/Sender/FCMSender.php#L73

**Comment by Stevemoretz** [comment]
But what about sending multiple group_keys at the same time,that's what is needed not changing the docs :(
Imagine sending to 1000 groups ,
you have to send 1000 requests instead of sending a payload with 1000 ids

**Comment by williamdes** [comment]
Sure, I will have a look at what the actual code supports
If it can handle an array I will do a fix :)

**Comment by williamdes** [comment]
As you can see with 4acf2717da240059ebf6903f69e44add48ec2ea1 all tests pass without an error
Could you please send me the full stacktrace ?

**Comment by Stevemoretz** [comment]
Hi dude,very nice that it all works yeah I've tested it manually myself too and it works.

`Could you please send me the full stacktrace ?`
What stacktrace?

Oh sorry I thought this was a message in pull request.

So are you telling me that group with arrays work?

Because it checked fcm docs and a few places looks like actually this is impossible to do.

**Comment by williamdes** [comment]
Hi

> What stacktrace?

The error trace ?

Maybe we did not understand the same thing, could you let me know the:
- Described issue
- Expected behavior
- Actual behavior

**Comment by Stevemoretz** [comment]
The issue is using:

```php
$notificationBuilder = new PayloadNotificationBuilder('my title');
$notificationBuilder->setBody('Hello world')
                        ->setSound('default');

$notification = $notificationBuilder->build();

$notificationKey = ['a_notification_key'];

$groupResponse = FCM::sendToGroup($notificationKey, null, $notification, null);

$groupResponse->numberSuccess();
$groupResponse->numberFailure();
$groupResponse->tokensFailed();
```

Since $notification Key is an array it doesn't send any messages but if using string one group_key instead it will send it.

**Comment by williamdes** [comment]
Oh, okay I understand now
I will improve my test

**Comment by williamdes** [comment]
Hi @Stevemoretz 
I added more tests and you can see all the group keys are sent to the server in ba05a9540440f2049627f299b3201d5885485ff4

So, did I miss something ?
