### ISSUE TITLE
Laravel 8 Support?

### ISSUE THREAD

**Issue by exzachlyvv** [code-lts/Laravel-FCM#8]
After upgrading to Laravel 8,

I am seeing this error: `Undefined property: LaravelFCM\FCMManager::$app`

on `FCMManager.php(12):`

**Comment by williamdes** [comment]
Indeed, [7.x](https://github.com/laravel/framework/blob/7.x/src/Illuminate/Support/Manager.php#L25) has `$app` and [8.x](https://github.com/laravel/framework/blob/8.x/src/Illuminate/Support/Manager.php) does not

**Comment by williamdes** [comment]
Hi @exzachlyvv 
Could you please let me know if my fix works fine for you ?
Using the `dev-main` version of this package (https://packagist.org/packages/code-lts/laravel-fcm#dev-main)

**Comment by alr2413** [comment]
I've tested the `dev-main` version of your package, and it's working perfectly.
Thanks.

**Comment by williamdes** [comment]
I released [1.6.0](https://github.com/code-lts/Laravel-FCM/releases/tag/1.6.0) :tada:
